#!/bin/bash
# P2: the real-image replication.
#
# Everything in the synthetic study is generated by our own renderer, which is what makes the
# counterfactual control exact and is also its most obvious limitation. This runs the identical
# protocol on COCO photographs, with counterfactuals that are exact by a different route --
# a horizontal flip, a segmentation-masked paste, a redrawn glyph box -- each guarded by a pixel
# identity check in gen/verify_real.py rather than by a re-render hash.
#
# The dataset is built and verified before this script runs (gen/build_real.py, gen/verify_real.py).
set -e
PY=.venv/bin/python
D=data/real_3b

echo "=== 1. behaviour ==="
$PY run/score.py --data $D --out runs/real_gen.jsonl --base-only --gen-only 2>&1 | tail -1
echo "=== 2. hidden states (eager) ==="
$PY run/capture.py --data $D --out runs/states_real.npz 2>&1 | tail -1
echo "=== 3. G1 presence test ==="
$PY run/probe.py runs/states_real.npz 2>&1 | grep -viE 'warn|converg|explained_var'
echo "=== 4. freeze probes ==="
$PY run/fit_probes.py runs/states_real.npz runs/probes_real.npy 2>&1 | grep -viE 'warn|converg'
echo "=== 5. layer sweep vs the model's own accuracy ==="
$PY run/layers.py runs/states_real.npz runs/real_gen.jsonl runs/layers_real.json 2>&1 \
    | grep -viE 'warn|converg|explained_var'
echo "=== 6. counterfactual control (prebuilt, exact) ==="
$PY run/cfprobe.py --data $D --probes runs/probes_real.npy --prebuilt \
    --res runs/cfprobe_real.json 2>&1 | grep -v "it/s" | tail -14
echo "=== STAGE13 DONE ==="
